dist: trusty

language: node_js

node_js:
  - "10"
  - "12"
  - "14"

branches:
  only:
    - master

addons:
  chrome: stable

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Headless chrome
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # Tests
  - yarn run test

after_script:
  - yarn codecov

cache:
  yarn: true
  directories:
    - node_modules
